server:
  port: 9002
spring:
  profiles:
    active: local
---
spring.profiles: local, test
mailgun:
  key: "66a409cfdfb014529f4cc262f8e47139-a5d1a068-9d376f60"
  from: "Mailgun Sandbox <postmaster@sandboxbe75f9faa11644058350d8a3962c043e.mailgun.org>"
  basePath: "https://api.mailgun.net/v3/sandbox846ff1cfb2174c0eb79bc126a7c3f2c6.mailgun.org"
  endpointuri: "https://api.mailgun.net/v3/sandbox846ff1cfb2174c0eb79bc126a7c3f2c6.mailgun.org/messages?from=Test@sandbox846ff1cfb2174c0eb79bc126a7c3f2c6.mailgun.org&to=sujatha.bandi@outware.com.au&subject=hello&text=testing"
sendGrid:
  key: "Bearer SG.NgM340d_So2ks7Kicgaj5Q.MS__c_7IWQ3iItLllMp7sYM7M4-saU6cjODLdjXjzL0"
  from: "sujathab03@gmail.com"
  endpointuri: "https://api.sendgrid.com/v3/mail/send"

---
spring.profiles: prod
#define prod utls and keys here